# Generated by Django 5.1.1 on 2024-09-24 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_transaction_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="note",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
