services:
  backend:
    container_name: et_backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    env_file:
      - backend/.env
    restart: always
    volumes:
      - ./backend:/app
  celery:
    container_name: et_celery_dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery --app=core worker --loglevel=info --pool=prefork -c 2
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app

    depends_on:
      - backend
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - '6397:6379'
