[mypy]

plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

exclude = core/

[mypy.plugins.django-stubs]
django_settings_module = "core.settings.base"


[mypy.plugins.djangorestframework-stubs]


[mypy-core.settings.base]
ignore_errors = true


