# Generated by Django 5.1.1 on 2025-05-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.CharField(db_index=True, max_length=7, unique=True)),
                ("first_team", models.CharField(max_length=150)),
                ("second_team", models.CharField(max_length=150)),
                ("start", models.CharField(max_length=100)),
                ("league_name", models.CharField(max_length=100)),
            ],
        ),
    ]
