# Generated by Django 5.1.5 on 2025-03-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={},
        ),
    ]
